// CalcQI — daily rotating "Did you know?" facts.
// One fact per day per calculator, cycling through a pool of 10.
// Keys are the calculator page filenames.
// Entries marked "Myth:" or "Legend says" are folklore; the rest are factual.
window.CALCQI_FACTS = {
  'percentage-calculator.html': [
    'The % symbol evolved from the Italian phrase "per cento" meaning "for a hundred", later compressed to "per 100" and then the % glyph.',
    'One basis point equals 0.01% — so 100 basis points equal a whole percentage point.',
    'A 50% increase followed by a 50% decrease leaves you at 75% of your original value, not 100%.',
    'Percentages in finance are often annualized so different terms can be compared fairly.',
    'The word "percent" literally means "per hundred" — from Latin "per centum".',
    'A discount of 20% followed by another 20% is 36% off total, not 40% — percentages don\u2019t simply add.',
    'Percentages can only be added to percentages of the same base.',
    'Interest rates quoted as APR in many countries include fees, not just the raw rate.',
    'Myth: "percentages and percentage points are the same" — a rise from 5% to 6% is 1 percentage point but a 20% increase.',
    'The concept of per-cent calculations appears in ancient Roman tax documents using "per centum".'
  ],
  'tip-bill-split-calculator.html': [
    'In the US, 15% is the baseline tip, 18–20% is customary for good service, and 25%+ for exceptional.',
    'The word "tip" may come from 18th-century coffee houses with a jar labelled "To Insure Promptness".',
    'Tipping norms vary wildly by country — many places include service in the bill.',
    'Etiquette often says tip on the pre-tax amount, though most people tip on the total.',
    'Splitting a bill equally is the fastest approach but ignores who ordered more.',
    'Some restaurants include an automatic gratuity for large parties — check before adding a second tip.',
    'Digital pay screens now commonly prompt tips for takeaway and counter service too.',
    'A tip of 20% on a $50 meal is $10 — the same as a 10% tip on $100.',
    'Legend says the word "tips" was once an acronym for "To Insure Prompt Service", but linguists doubt it.',
    'Tipping for to-go orders became far more common after 2020.'
  ],
  'body-fat-percentage-calculator.html': [
    'Body fat percentage is the fraction of your total weight made up of fat tissue.',
    'Essential body fat is roughly 3–5% for men and 10–13% for women — below this is dangerous.',
    'The US Navy method estimates body fat from neck, waist, and height measurements.',
    'Skinfold callipers measure fat in millimetres at standard sites and convert to a percentage.',
    'Bioelectrical impedance — used by home scales — estimates water content to infer fat.',
    'An athlete at 6–10% body fat is often described as "lean"; healthy ranges extend to ~24% (men) and ~31% (women).',
    '1 kg of stored fat holds about 7,700 kcal of energy.',
    'Body fat percentage matters more than the scale for tracking health and physique changes.',
    'DEXA scans are considered a clinical gold standard for body composition.',
    'Myth: "you can spot-reduce fat with targeted exercise" — fat loss is whole-body, not local.'
  ],
  'calories-burned-calculator.html': [
    'One MET equals the energy burned while sitting still — about 1 kcal per kg of body weight per hour.',
    'Running at 10 km/h burns roughly 10–11 METs — over 10× resting energy.',
    'The 3500-kcal rule suggests about 0.45 kg of fat per 3,500 kcal deficit.',
    'Cycling at a brisk pace typically burns 7–8 METs.',
    'Swimming is a full-body MET-excellent workout, around 8–10 METs.',
    'Heavier people burn more calories for the same activity because more mass moves.',
    'Walking at a normal pace is around 3.5 METs.',
    'After intense exercise, EPOC (excess post-exercise oxygen consumption) raises burn slightly for hours.',
    'Most gym machines overestimate calories burned — real burn is often lower.',
    'Myth: "cardio is the only way to burn calories" — strength training burns during and after.'
  ],
  'unit-converter.html': [
    'The nautical mile is defined by the Earth\u2019s circumference — one minute of latitude equals roughly one nautical mile.',
    'One inch is exactly 2.54 centimetres by international definition.',
    'A US gallon (3.785 L) is smaller than a UK imperial gallon (4.546 L).',
    'The kilogram was redefined in 2019 in terms of the Planck constant, not a physical object.',
    'Water at 4°C is densest — 1 litre weighs almost exactly 1 kilogram.',
    'Room temperature is about 20–25°C, 68–77°F.',
    'The mile is 5,280 feet because 1,760 yards were standardised by Queen Elizabeth I.',
    'A foot was originally based on the average human foot — about 30.48 cm.',
    'Absolute zero is −273.15°C, −459.67°F, or 0 kelvin.',
    'Myth: "Fahrenheit and Celsius are just negatives of each other" — they meet only at −40°.'
  ],
  'age-date-difference-calculator.html': [
    'The Gregorian calendar was introduced in 1582 and is the most widely used civil calendar today.',
    'Leap years are skipped every 100 years unless divisible by 400 — so 2100 will not be a leap year.',
    'The Unix epoch (1 January 1970) is the starting point for most modern computing time.',
    'The oldest verified person, Jeanne Calment, lived to 122 years and 164 days.',
    'You reach roughly 1 billion seconds of life at about age 31.7.',
    'February 29 is the rarest birthday on the Gregorian calendar.',
    'Time zones were standardised in the late 19th century — before that, every city set its own noon.',
    'Average life expectancy worldwide is around 73 years.',
    'Age in "months and days" often differs by whether you count the starting day.',
    'Myth: "time moves slower as you age" — it feels that way, but a year is always 365 (or 366) days.'
  ],
  'discount-sale-price-calculator.html': [
    'The word "discount" comes from the Latin "discomputare" — to count differently.',
    'Black Friday began in the US as the day after Thanksgiving when retailers aimed to move "into the black".',
    'A 50% discount followed by a further 20% off is a 60% total discount, not 70%.',
    'The "9-ending" pricing trick (like $19.99) exploits left-digit anchoring in buyers\u2019 minds.',
    'Seasonal sales often mark up prices first, then discount them — check the baseline.',
    'Buy-one-get-one-free is effectively a 50% discount when you need two items.',
    'Retail studies show discounts of 20% or more feel meaningful to buyers; smaller ones often go unnoticed.',
    'The word "bargain" originally meant a deal or negotiation, not necessarily a low price.',
    '"Days of our Lives" style doorbuster sales can involve loss leaders — items sold below cost.',
    'Myth: "a discount always means a good deal" — the original price is not always the real baseline.'
  ],
  'fuel-cost-calculator.html': [
    'The most fuel-efficient speed for most cars is around 80–90 km/h (50–56 mph).',
    'Idling can consume about half a gallon (about 2 L) of fuel per hour.',
    'Driving at 120 km/h instead of 100 km/h can increase fuel consumption by roughly 20%.',
    'Air conditioning uses more fuel than open windows at highway speeds, but the reverse is true in the city.',
    'A litre of petrol and a litre of diesel have almost the same volume but diesel packs more energy.',
    'Aggressive acceleration and braking can lower fuel economy by 15–30% at highway speeds.',
    'Under-inflated tyres increase rolling resistance and can cut fuel economy by a few percent.',
    'The world record for the most fuel-efficient production car exceeds 3 L/100km (about 78 MPG).',
    'Premium petrol rarely improves fuel economy unless the engine requires it.',
    'Myth: "you get more fuel when you fill up slowly" — pump meters are accurate either way.'
  ],
  '3d-print-cost-calculator.html': [
    'The first 3D printer patent was filed by Chuck Hull in 1984.',
    'FDM (fused deposition modeling) was invented by Scott Crump in 1989.',
    'An average spool of PLA filament costs roughly $20–25 for a kilogram.',
    'Electricity for a 6-hour print at average rates costs only tens of cents.',
    'Resin printers can produce finer detail than FDM but require more cleanup and post-curing.',
    'The "3D printing cost per gram" can be found by dividing spool cost by spool weight.',
    'PETG is more temperature-resistant and flexible than PLA, making it a popular upgrade.',
    'Printing at higher infill uses more filament, so a 10% infill is common for decorative parts.',
    'The term "stl" stands for STereoLithography — the file format most 3D printers use.',
    'Myth: "3D printing is always cheap" — expensive resins and long print times can add up fast.'
  ],
  'pizza-dough-calculator.html': [
    'Neapolitan pizza dough typically uses just flour, water, salt, and yeast — no oil.',
    'A 65% hydration dough means water is 65% of the flour weight — a classic chewy ratio.',
    'Cold fermentation (24–72 hours in the fridge) develops flavour without extra yeast.',
    'High-gluten or bread flour helps achieve a crispy, chewy crust.',
    'Yeast amount matters less than time and temperature for flavour development.',
    'Salt in dough strengthens the gluten and controls fermentation speed.',
    'A 250g dough ball is typical for a 12-inch Neapolitan pizza.',
    'Using a baking steel or stone at 250°C+ mimics a wood-fired oven at home.',
    'The "windowpane test" shows when gluten is developed enough to stretch.',
    'Myth: "more yeast means more flavour" — long slow fermentation yields more flavour than extra yeast.'
  ],
  'ny-style-pizza-dough-calculator.html': [
    'New York-style dough is typically 60% hydration with a relatively high amount of high-gluten flour.',
    'NY-style pizza is usually hand-tossed and large — 14 to 16 inches is common.',
    'Cold-fermenting the dough for 24–72 hours is a hallmark of great New York slices.',
    'The iconic "foldable slice" relies on a crust that is crisp yet supple.',
    'A typical 14-inch dough ball weighs around 340g (12 oz).',
    'NY pizza ovens often run hotter than home ovens, producing a faster, crispier bake.',
    'Sugars like honey or malt can help the crust brown at lower temperatures.',
    'The NY style evolved in the early 1900s as Italian-American bakeries turned to pizza.',
    'Some New York pizzerias use "00" flour blended with bread flour for the right chew.',
    'Myth: "New York pizza needs New York water" — a fun claim, but not scientifically supported.'
  ],
  'cnc-laser-cutting-cost-calculator.html': [
    'CNC stands for Computer Numerical Control — machines follow programmed instructions.',
    'Lasers cut by vaporising material; they leave a kerf (width of cut) that affects part fit.',
    'A 100W CO2 laser can cut wood up to ~20mm thick depending on the material.',
    'Cutting speed and feed rate trade off: too fast and the beam doesn\u2019t penetrate; too slow and it burns.',
    'Laser cutting works best on flat sheet material; CNC routers handle thicker stock.',
    'The hourly rate for a laser cutter often includes machine wear, gas, and power costs.',
    'Nesting parts closely together on a sheet reduces waste and cost.',
    'Engraving removes only the surface, so it uses less time and power than full cutting.',
    'Air assist improves edge quality by blowing away smoke and debris.',
    'Myth: "lasers can cut anything" — metals over a few mm generally need fibre lasers or different processes.'
  ],
  'sourdough-levain-calculator.html': [
    'A 1:2:2 levain build means 1 part starter, 2 parts flour, 2 parts water.',
    'Sourdough\u2019s tang comes from lactic and acetic acids produced by the wild yeast and bacteria.',
    'A higher inoculation (more starter) speeds up fermentation; lower slows it down.',
    'The "float test" — a ripe levain floats in water — is a common readiness check.',
    'Dough hydration of 75% or higher creates a more open, airy crumb.',
    'Cold proofing in the fridge (12–48h) builds flavour while slowing activity.',
    'The starter is a living culture — regular feeding keeps it healthy.',
    'The leaven adds billions of wild yeast cells, giving sourdough its signature complexity.',
    'Salt (usually ~2% of flour weight) strengthens gluten and controls fermentation.',
    'Myth: "sourdough is gluten-free" — the fermentation reduces but does not eliminate gluten.'
  ],
  'resin-casting-volume-calculator.html': [
    'Volume is length × width × height — for a rectangular mold, that\u2019s simply L×W×H.',
    'A 1cm × 1cm × 1cm cube is 1 cubic centimetre = 1 millilitre.',
    'Epoxy resin and hardener usually mix in a strict ratio, often 2:1 or 1:1 by volume.',
    'Resin density is about 1.1 g/ml for many clear casting epoxies.',
    'Pouring a little extra resin (a "buffer") compensates for the meniscus and bubbles.',
    'Most molds recommend a 10% overage to avoid running short.',
    'The total resin needed in grams ≈ volume (ml) × density (g/ml).',
    'For a 2:1 ratio, two-thirds of the total is resin and one-third hardener.',
    'Casting resin cures by exothermic reaction — large, deep pours can overheat.',
    'Myth: "you can add more hardener to speed it up" — that ruins the cure entirely.'
  ],
  'video-bitrate-file-size-calculator.html': [
    'File size = bitrate × duration / 8 — bitrate is in bits, file size in bytes.',
    'A 1-hour 4K video at 60 Mbps is about 27 GB.',
    'YouTube recommends around 45–68 Mbps for 4K 60fps uploads.',
    '1080p Blu-ray discs average about 25–35 Mbps.',
    'H.265 (HEVC) can deliver similar quality at about half the bitrate of H.264.',
    'A 10-minute 1080p video at 10 Mbps is about 750 MB.',
    'Higher resolution needs higher bitrate to look clean — 4K at low bitrate looks soft.',
    'The number 8 converts Megabits to Megabytes.',
    'Streaming services often use adaptive bitrate so quality changes with connection speed.',
    'Myth: "higher bitrate always means better quality" — past a point, it adds no visible benefit.'
  ],
  'depth-of-field-calculator.html': [
    'Depth of field shrinks as aperture widens — f/2.8 blurs backgrounds far more than f/11.',
    'Hyperfocal distance is the focus point where everything from half that distance to infinity is sharp.',
    'Aperture is expressed as f-numbers; a lower number means a wider opening.',
    'Longer focal lengths compress apparent depth of field at the same aperture.',
    'Circle of confusion (CoC) is the accepted blur limit used in DOF formulas.',
    'For full-frame cameras, CoC is commonly taken as 0.029 mm.',
    'Background separation is easier with a 50mm f/1.8 than a 24mm f/4.',
    'DOF increases as you focus farther away — up to the hyperfocal distance.',
    'Macro lenses have very shallow DOF, often just millimetres.',
    'Myth: "a bigger aperture always gives a shallower depth of field" — distance and focal length matter too.'
  ],
  'camera-field-of-view-calculator.html': [
    'Horizontal FOV = 2 × atan(sensor width / (2 × focal length)).',
    'A 50mm lens on full-frame gives roughly a 40° horizontal field of view.',
    'Crop factor converts a lens to "full-frame equivalent" focal length.',
    'A 35mm APS-C lens behaves like a 52.5mm lens on full frame (1.5× crop).',
    'The "35mm equivalent" standard comes from the classic 35mm film frame.',
    'Full-frame sensors are 36mm × 24mm.',
    'Smartphone main cameras are often ~26mm equivalent — quite wide.',
    'A focal length of 85mm gives about a 24° horizontal FOV — great for portraits.',
    'Ultra-wide lenses (<24mm) exaggerate perspective and stretch edges.',
    'Myth: "longer lenses always magnify the background" — they compress perspective, not magnify the subject.'
  ],
  'nd-filter-exposure-calculator.html': [
    'An ND filter reduces light entering the lens so you can use longer exposures or wider apertures.',
    '10 stops is 2^10 = 1024× less light — the classic "ND1000" for daytime long exposures.',
    'A 3-stop ND lets in 1/8 of the light; a 10-stop lets in about 1/1000.',
    'Neutral density filters are rated in stops: ND2 = 1 stop, ND4 = 2, ND8 = 3, etc.',
    'Long exposures turn moving water into smooth silk.',
    'The exposure time multiplies by 2 for every stop: 1/250s with 10 stops becomes 4 seconds.',
    'Stacking multiple NDs adds their stops together but can introduce vignetting.',
    'Variable ND filters rotate to change density — handy but can show cross-pattern artefacts.',
    'ND filters also help videographers shoot at the "180-degree rule" shutter in daylight.',
    'Myth: "ND filters make everything darker" — they reduce light so you can keep aperture and shutter open longer.'
  ],
  'timelapse-interval-calculator.html': [
    'A timelapse hyperlapse (moving timelapse) requires consistent camera movement.',
    'The number of shots needed = clip length (s) × frame rate (fps).',
    'A 10-second clip at 30 fps needs 300 frames.',
    'For a 60-minute event and 300 shots, an interval of 12 seconds works well.',
    'Star trail timelapses commonly use 20–30 second exposures with 1–5 second gaps.',
    'Timelapses compress days into seconds — a 2-hour sunset into 10 seconds.',
    'Shutter intervals below 1 second can cause flicker and motion blur.',
    'Typically 25–30 fps playback is used for smooth timelapse videos.',
    'The "interval" is how often the camera fires — not the shutter speed.',
    'Myth: "timelapses need special gear" — any camera with an intervalometer works.'
  ],
  'light-falloff-inverse-square-calculator.html': [
    'Light intensity falls off with the square of distance: double the distance, quarter the brightness.',
    'The inverse-square law: intensity ∝ 1/d².',
    'Moving a light from 2m to 4m reduces its light to 25% (one quarter).',
    'Each 1.414× increase in distance halves the light (one stop).',
    'Doubling distance = 4× less light — a 2-stop loss.',
    'The law applies to point sources; large softboxes fall off more gently.',
    'In photography, closer lights = softer, brighter falloff across your subject.',
    'Lux and foot-candles both measure illuminance; 1 fc ≈ 10.76 lux.',
    'The sun is so far that its light is effectively parallel — no practical falloff.',
    'Myth: "the inverse-square law means moving lights matters little" — it\u2019s one of the biggest levers in lighting.'
  ],
  'tdee-macro-calculator.html': [
    'TDEE = Total Daily Energy Expenditure = BMR × activity factor.',
    'BMR is the energy your body burns at rest — about 60–70% of your daily burn.',
    'The Mifflin-St Jeor equation is one of the most accurate BMR formulas.',
    'Cutting about 500 kcal/day typically loses ~0.5 kg per week.',
    'Protein needs for muscle gain are around 1.6–2.2 g per kg of body weight.',
    'Carbohydrates and fat both provide 4 and 9 kcal per gram respectively.',
    'Activity factors range from 1.2 (sedentary) to 1.9+ (very active).',
    'A 20% calorie deficit is generally sustainable for fat loss.',
    'Maintenance calories aren\u2019t fixed — they shift as weight, muscle, and activity change.',
    'Myth: "you must eat 6 meals a day to boost metabolism" — meal frequency matters little.'
  ],
  'one-rep-max-calculator.html': [
    'The Epley formula estimates 1RM as W × (1 + reps/30).',
    'The Brzycki formula is W × 36/(37 − reps).',
    'Estimates are most accurate for reps in the 1–10 range.',
    'True 1RM testing is risky — estimation formulas are safer.',
    '1RM typically decreases as reps increase, but the relationship isn\u2019t perfectly linear.',
    'Epley and Brzycki can differ by a few kg at high rep counts.',
    'A common goal: a 3-rep max estimates within ~2% of true 1RM.',
    'Lifting your 1RM once is safer with a spotter or safety bars.',
    'Your 1RM changes with fatigue, sleep, and nutrition.',
    'Myth: "your 1RM is fixed" — it\u2019s a snapshot, not a permanent number.'
  ],
  'ffmi-muscular-potential-calculator.html': [
    'FFMI normalises muscle mass per height: (weight × (1 − body fat%)) / height².',
    'A natural male typically maxes out around 25 FFMI; 26–28 is exceptional.',
    'The average male athlete sits around 22–24 FFMI.',
    'FFMI was introduced by Kouri et al. in 1995 showing the natural ceiling near 25.',
    'Normalizing FFMI adjusts for height: ~6.1 × (1.80 − height in m).',
    'Body fat must be estimated to compute lean mass — measurements matter.',
    'A woman\u2019s natural FFMI ceiling is lower, usually around 21–22.',
    'FFMI alone doesn\u2019t capture frame size or bone density.',
    'Lean mass greater than ~25 FFMI is very hard to achieve without enhancement.',
    'Myth: "you can keep gaining muscle forever on a bulk" — there\u2019s a natural ceiling.'
  ],
  'wilks-dots-powerlifting-calculator.html': [
    'Wilks coefficient compares lifts across bodyweights using a formula.',
    'DOTS (Departed Opponent Total Score) is a modern replacement for Wilks.',
    'A DOTS of 400+ is considered elite in most federations.',
    'Wilks was created in the 1990s by Bob Wilks for powerlifting comparisons.',
    'Coefficients are lower for heavier lifters — they need higher totals to match.',
    'DOTS was designed to reduce the "bigger is better" bias of older formulas.',
    'Both formulas use different coefficients for men and women.',
    'A 75kg lifter and a 120kg lifter can compare fairly using these scores.',
    'Wilks is used by many meet directors to rank lifters across weight classes.',
    'Myth: "a high Wilks always means you\u2019re strong" — technique and federation rules matter too.'
  ],
  'karvonen-heart-rate-zone-calculator.html': [
    'Karvonen uses heart rate reserve: (Max HR − Resting HR) × % + Resting HR.',
    'Max HR is often estimated as 220 − age.',
    'Zone 2 is roughly 60–70% of heart rate reserve — great for endurance.',
    'Zone 5 (>90%) is for maximal intervals.',
    'Your resting heart rate is usually taken first thing in the morning.',
    'A healthy resting heart rate ranges from about 60–100 bpm, athletes often lower.',
    'The "reserve" concept accounts for your personal fitness level.',
    '220 − age is an estimate; real max HR varies widely between people.',
    'High-intensity work happens at 80–90% of heart rate reserve.',
    'Myth: "all training should be in the red zone" — most training should be easy.'
  ],
  'running-pace-calculator.html': [
    'Pace is the time taken per distance — e.g. minutes per kilometre or mile.',
    'A 5:00 min/km pace means 5 km in 25 minutes.',
    'Marathon pace is typically about 10–15 seconds per km slower than 10k pace.',
    'Speed = distance / time; pace = time / distance.',
    'Most runners aim for 180 steps per minute (cadence) — a common target.',
    'A 10k in 40 minutes is a 4:00/km pace — quite respectable.',
    'Age grading compares your time to the best possible for your age and sex.',
    'Negative splits (running the second half faster) are the pro approach.',
    'A 30-minute 5k is a common benchmark for recreational runners.',
    'Myth: "you must run fast to be a runner" — any consistent pace counts.'
  ],
  'stock-average-down-calculator.html': [
    'Averaging down lowers your cost basis by buying more shares at a lower price.',
    'Dollar-cost averaging is buying fixed dollar amounts on a schedule.',
    'Break-even = total invested ÷ total shares.',
    'Averaging down can amplify gains when the price recovers.',
    'It also increases your risk if the price keeps falling.',
    'A 50% drop requires a 100% gain to return to break-even.',
    'Fresh capital invested at a lower price reduces your average cost.',
    'Some investors only average down if fundamentals still look strong.',
    'Averaging down is a form of adding to a losing position.',
    'Myth: "dollar-cost averaging always beats lump sum" — statistically, lump sum often wins.'
  ],
  'dividend-drip-calculator.html': [
    'DRIP stands for Dividend Reinvestment Plan.',
    'Reinvesting dividends compounds returns — each dividend buys more shares.',
    'A 4% dividend yield reinvested adds up enormously over 10 years.',
    'DRIPs usually buy fractional shares automatically.',
    'Compounding dividends is why long-term holders outperform.',
    '10 years of reinvesting a 3% yield on $10,000 roughly doubles your dividend income.',
    'Dividend aristocrats are companies with 25+ years of raising dividends.',
    'Reinvested dividends remove the temptation to spend the cash.',
    'Most brokers offer free fractional DRIPs on major stocks.',
    'Myth: "dividends are free money" — the stock price drops by the dividend amount on ex-date.'
  ],
  'position-size-risk-calculator.html': [
    'Risk per trade = account equity × risk percentage (e.g. 1%).',
    'Position size = risk amount ÷ (entry − stop loss).',
    'Risk-reward (R:R) = (target − entry) ÷ (entry − stop loss).',
    'A 1% risk on a $25,000 account is a $250 max risk.',
    'Common rule: risk no more than 1–2% of your account per trade.',
    'Stop losses define your risk; targets define your reward.',
    'A 1:2 R:R means risking $100 to make $200.',
    'Position sizing protects you from a single bad trade wiping you out.',
    'Higher probability setups can justify smaller R:R ratios.',
    'Myth: "bigger position = bigger returns" — it also means bigger risk.'
  ],
  'compound-interest-calculator.html': [
    'The Rule of 72: divide 72 by the interest rate to approximate doubling time.',
    'At 6% annual interest, money doubles in about 12 years (72 ÷ 6).',
    'Monthly vs yearly compounding barely differs at typical rates.',
    'A 1% higher rate can be worth tens of thousands over 30 years.',
    'Time is the most powerful factor in compound growth.',
    '$5,000 at 7% for 30 years grows to ~$38,000 without extra deposits.',
    'Adding monthly deposits supercharges compounding.',
    'Compound interest is sometimes called the "eighth wonder of the world".',
    'Compounding works against you on debt too — credit card interest compounds monthly.',
    'Myth: "interest rates don\u2019t matter much" — over decades they matter enormously.'
  ],
  'crypto-roi-calculator.html': [
    'Crypto ROI = (sell price − buy price) ÷ buy price × 100.',
    'Fees (buy + sell) reduce your net ROI — always subtract them.',
    'Bitcoin was first valued at fractions of a cent and is now five figures.',
    'A 100% gain then a 50% loss puts you back at break-even.',
    'Volatility cuts both ways — a coin can double or halve in a week.',
    'ROI doesn\u2019t account for taxes or transfer fees unless you include them.',
    'Crypto returns are typically higher but far riskier than stocks.',
    'The "HODL" meme originated from a typo of "hold" in a 2013 forum post.',
    'Leverage trading multiplies both gains and losses.',
    'Myth: "past crypto gains predict future returns" — past performance never guarantees future results.'
  ],
  'mortgage-payment-calculator.html': [
    'The word "mortgage" comes from old French — literally "death pledge".',
    'Monthly payment = P × r(1+r)^n ÷ ((1+r)^n − 1).',
    'A 1% lower rate can save tens of thousands over 30 years.',
    'Down payment reduces the loan principal and the interest paid.',
    'A 30-year loan at 6% costs almost double the home price in total payments.',
    'Extra monthly payments reduce both principal and total interest.',
    'Amortisation means early payments are mostly interest, later mostly principal.',
    'LTV (loan-to-value) determines if you need mortgage insurance.',
    'A 20% down payment historically avoids PMI.',
    'Myth: "you should always put 20% down" — lower down payments are often perfectly fine.'
  ]
};